spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: config-reader
      containers:
        - livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
