spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: config-reader
#      volumes:
#        - name: config
#          configMap:
#            name: ${project.artifactId}
#            items:
#              - key: application.yaml
#                path: application.yaml
      containers:
        -
#          volumeMounts:
#            - name: config
#              mountPath: /workspace/config
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
